### ISSUE TITLE
package.json에 엔진 버전 명시가 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/web-lab#10]
# 설명
Heroku가 `package.json`의 필드들을 참조해 Node 등 런타임의 버전을 결정하기 때문에, 버전 이슈를 방지하기 위해 버전 명시가 필요합니다.
현재 Heroku 배포시 다음과 같은 메세지가 보입니다.

```
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.11.4...
remote:        Using default npm version: 5.6.0
remote:        Resolving yarn version 1.x...
remote:        Downloading and installing yarn (1.10.0)...
remote:        Installed yarn 1.10.0
```

[Heroku가 권장하는 Node.js setup best practice](https://devcenter.heroku.com/articles/node-best-practices) 를 참고하면 되겠습니다.

**Comment by JeongHoJeong** [comment]
@limgit 혹시 이 이슈도 맡아주실 수 있나요? `package.json`에 다음 내용을 포함해 몇몇 manifest만 마저 추가하면 될 것 같습니다.
```json
"engines": {
  "node": "8.11.4"
}
```

**Comment by limgit** [comment]
```json
"engines": {
  "node": "8.11.4",
  "npm": "5.6.0",
  "yarn": "1.10.0"
}
```
이 필요한가요? 이슈 이해가 잘 안되네요

**Comment by JeongHoJeong** [comment]
네 그게 맞을 것 같습니다. `npm` 버전은 명시가 필요할지 모르겠네요. 가능하면 `yarn`만 쓰게 하고 싶은데...

**Comment by limgit** [comment]
[이 문서](https://devcenter.heroku.com/changelog-items/1065) 에 따르면 `yarn.lock`이 깃에 포함되어 있는 경우 Heroku가 프로젝트 매니저로 yarn을 쓰는 것 같습니다. npm은 default 값이라 우선 설치하고 보는 것 같은데 어차피 yarn을 쓰는거라면 npm 버전 명시는 필요 없을 것 같긴 하네요

**Comment by JeongHoJeong** [comment]
https://docs.npmjs.com/files/package.json
위를 참고하셔서 보실 때 빠진 내용이 있다면 채워주셔도 좋을 것 같습니다. Heroku가 알게모르게 참조하는 사항들이 많은 것 같아요. @limgit

**Comment by JeongHoJeong** [comment]
어사인 해 드려도 될까요? @limgit

**Comment by limgit** [comment]
했습니당~ ㅎㅎ
