### ISSUE TITLE
기초 기능 구현이 필요합니다.

### ISSUE THREAD

**Issue by limgit** [binarysound/web-lab#19]
# 설명
#1 에서 논의했던 대로, 우선 핵심 기능에 해당하는 "게임 로직" 부분을 먼저 구현하고, 이후에 다른 페이지를 구현하며 살을 붙여나가는 방향이 좋을 것 같습니다. 다른 페이지 부분을 나중에 구현하기 때문에 각 페이지가 담당하고 있는 기능 중 게임 진행에 필요한 부분만을 간단히 구현해야 합니다.
Game Page에서 크게 필요한 기능들은 다음과 같습니다:

- 게임 로직
- 적어도 테스트 게임을 돌려볼 수는 있을 정도로 구현된 간단한 방 기능
   - 방 생성 등의 기능을 구체적으로 구현하는 것이 아니라, 그냥 특정 페이지 (ex. `/game`)에 최초로 접근한 사람을 방장으로, 이후에 접근하는 사람들을 멤버로 설정하고, 방장이 게임 시작을 할 수 있도록 함
   - 혹은 그냥 두명 이상의 멤버가 차는 순간 바로 게임을 자동으로 시작하게 하는 방법도 있을 듯 (테스팅 단계에서만)
- 게임에서 필요한 최소 수준의 유저 식별 기능
   - 본래 Authentication 과정을 Login Page에서 진행하고 이를 기반으로 유저 식별을 해야하나, 현재 단계에서는 게임 기능 구현을 우선으로 두고 유저 식별 기능을 단순히 쿠키 or 세션을 이용하여 랜덤 스트링등의 유니크 키값으로 구현

이외에 어떤게 더 필요할지 당장은 생각나지 않네요. 생각나는대로 추가해주세요.

**Comment by JeongHoJeong** [comment]
개발에 앞서 전체적인 게임의 상태를 한 번 정의해보는 것은 어떨까요? 우선 게임에 대해 가지고 있는 서로의 멘탈 모델에 차이가 있으면 개발이 힘들텐데, 이를 수도 코드로라도 통합해보는 작업이 필요할 것 같다고 느껴서요. 결국 게임의 모든 것은 게임 상태에 대한 액션의 연속으로 귀결되므로, 상태 트리의 모양에 대해 먼저 논해보는 것은 어떨까 합니다.

```typescript
namespace NotABean {
  enum CardType {
    NUMBER, PLUS, MINUS,
  }

  interface ICard {
    type: CardType
  }

  interface IPlayer {
    id: number
    name: string
    isConnected: boolean
    hand: ICard[]
    /* ... */
  }
  interface IBoard { /* ... */ }

  export interface IGame {
    players: IPlayer[]
    board: IBoard[]
  }
}
```

위 상태 트리(`IGame`)의 구조가 확정되면 이제 상태 트리에 취할 액션들을 정의할 수 있습니다.

```typescript
enum GameActionType {
  /* ... */
}

interface IGameAction<T> {
  type: GameActionType
  payload: T
}
```

간단히나마 정리해 보았습니다. 플레이어가 보는 화면은 결국 위 상태 트리의 반영일 뿐이므로, 상태 트리만 견고하게 짜여진다면 개발은 순조로울 것이라 기대됩니다. 어떻게 생각하시나요? @limgit

**Comment by limgit** [comment]
말씀해주신 부분에 동의합니다 👍  요약하면, 게임을 일종의 오토마타로 기술하고 각 유저들은 매 순간 오토마타의 특정 state를 보며, 유저의 행동은 오토마타의 action으로 변환된다고 해석할 수 있겠네요.

그럼 상태 트리쪽을 견고하게 작성해두는게 필수적일 것 같습니다. 우선 떠오르는 추가할 내용은 다음과 같네요

```typescript
namespace NotABean {
  enum CardType {
    NUMBER, SPECIAL  // 변경됨
  }
  enum SpecialCard { // 추가됨
    NEGATION, DOUBLE, ZEROING
  }

  interface ICard {
    type: CardType
    cardValue: number | SpecialCard  // type에 따라 다른 타입의 값을 가짐
  }

  interface IPlayer {
    id: number
    name: string
    isConnected: boolean
    hand: ICard[]
    /* ... */
  }

  interface IBoard {
    cardsPlayed: // 여기에는 IPlayer, ICard 의 튜플의 배열이 와야 할 것 같습니다.
  }

  export interface IGame {
    players: IPlayer[]
    board: IBoard[]
    phase: number // 게임이 어느 단계에 돌입했는지를 나타냄. 그냥 숫자를 쓸 수도 있고 이에 맞는 enum을 따로 정의할수도 있음
  }
}
```
`IGame`의 `phase`는 한 라운드에서 게임이 어느 페이즈에 속해있는지를 나타냅니다. 선플레이어 플레이 / 다른 플레이어 플레이 / 카드 공개 / 카드 선택 / 선플레이어 결정 의 단계로 이루어지면 될 것 같고, 카드 공개 및 선 플레이어 결정 페이즈는 유저의 interaction 없이 정해진 규칙에 따라 상태를 변경하고 다음 페이즈로 넘어가면 됩니다.

이외에 
1. 현재 라운드의 선 플레이어가 누가 되는지를 표현하는 부분이 필요합니다
2. 각 플레이어가 획득한 카드 (가장 마지막에 점수 계산에 사용될 카드) 는 `IPlayer`에 속해야 할지, `IBoard`에 속해야 할지 애매하네요. 획득한 카드들은 모두에게 보이기도 하는 부분이라...

정도가 생각나네요

**Comment by JeongHoJeong** [comment]
- `phase`는 n 라운드의 의미가 아니라면 `enum`으로 두는 편이 좋겠습니다.
- `SpecialCard`를 분리하는 과정에 동의합니다. 다만, 이 부분은 좀 더 구체적인 생각이 필요할 것 같습니다. 예를 들어 위 제안해주신 모델로는 다음과 같이 게임 룰에 위반되는 assign에도 type error가 발생하지 않습니다.
```typescript
const card: ICard = {
  type: CardType.NUMBER,
  cardValue: SpecialCard.ZEROING,
}
```
따라서 다음 모양으로 하는 편이 type safe하지 않을까 싶습니다.
```typescript
enum CardType {
  NUMBER, SPECIAL,
}

enum SpecialCardValue {
  NEGATION, DOUBLE, ZEROING,
}

interface ICardBase<C extends CardType, V> {
  type: C
  value: V
}

type Card =
  ICardBase<CardType.NUMBER, number> |
  ICardBase<CardType.SPECIAL, SpecialCardValue>
```

또 고려해야 할 점이, 플레이어가 게임의 모든 정보를 쥐고 있어서는 안 되므로, 서버에만 있어야 하는 정보와 클라이언트에 전달되어야 하는 정보는 분리되어야 한다는 점입니다. 즉, 서버와 클라이언트가 각각 보고 있는 상태 트리가 조금 다를 필요가 있습니다. 이런 점은 어떻게 해결하는 것이 좋을까요? @limgit

**Comment by JeongHoJeong** [comment]
`cardsPlayed`는 다음과 같은 모양이 되면 좋겠습니다.
```typescript
interface IBoard {
  cardsPlayed: Array<{
    playerId: number,
    card: ICard,
  }>
}
```

**Comment by JeongHoJeong** [comment]
서버에만 있어야 하는 정보가 방금 말씀하신 것처럼 존재하지 않나요? 예를 들자면 상대 플레이어의 핸드가 어떤 것인지는 몰라야 하지 않을까요? 즉 서버가 가지고 있는 게임에 대한 모델과 클라이언트가 가지고 있는 모델이 100% 동일하다면, 클라이언트가 알고 있으면 안 되는 정보도 노출되지 않을까 하는 생각이었습니다.
클라이언트와 서버가 궁극적으로는 같은 정보 모델을 쥐고, 대신 클라이언트에는 일부 정보만 알려지는 식의 동작을 생각했기에 이런 말을 했습니다.

**Comment by limgit** [comment]
아 제가 서버에만 있는 정보를 이야기한건 진짜로 서버에만 있는 정보를 뜻한거긴 했습니다. 플레이어 핸드 정보의 경우 결국엔 해당 핸드를 들고 있는 클라이언트에게 정보가 가긴 하니까요.

저 역시 같은 정보모델을 쥐고 클라이언트에 일부 정보만 알린다는 방향에 대해 동의합니다. [이 코멘트](https://github.com/binarysound/web-lab/issues/19#issuecomment-420526120)도 그런 차원의 이야기구요. 머... 간단히 짜려면 그냥 다보내고 클라코드단에서 가려서 보이는 방법도 있겠지만요 😄

**Comment by JeongHoJeong** [comment]
음..... `서버에만 있는 정보`에 대한 해석이 서로 달랐던 것 같네요. 저는 어느 단 한 플레이어라도 해당 정보에 대해 모른다면 `서버에만 있는 정보`로 생각했고, @limgit 님은 그 어느 플레이어도 모르는 정보여야 `서버에만 있는 정보`로 생각하신 것 같습니다. 양쪽 다 일리 있다고 생각합니다.

이 관점의 차이에 대해 생각하다 좋은 솔루션이 하나 떠올랐습니다. 서버와 클라이언트가 공유해야 하는 게임 트리의 모든 leaf에 다음 정보를 붙이는 것은 어떨까 싶네요.

```typescript
type PlayerId = number

interface SharedInfo {
  __knownTo: PlayerId[],
}
```

공유되어야 하는 모든 정보가 `SharedInfo` 인터페이스를 상속하도록 하고, 게임 상태 트리 업데이트가 발생할 때마다 게임 트리 전체를 순회하며 `SharedInfo`인 인터페이스만을 클라이언트에 notify하는 모양은 어떻게 생각하시나요?

**Comment by limgit** [comment]
오 생각못한 방법이네요. 좋은 것 같습니다 👍 그럼 각 클라이언트별로 `if id in SharedInfo.__knownTo`인 경우에 정보를 받게 되겠네요. 다만 뭔가 그... 게임트리의 모든 leaf에 정보가 들어간다고 하니 왜인지 유지보수 비용이 증가할것만 같긴 합니다.
하나 더, `knownTo` 앞에 dunderscore가 붙는 이유가 따로 있나요?

**Comment by JeongHoJeong** [comment]
- 게임 트리의 모든 leaf라기보다는, 공유될 필요가 있는 모든 정보의 단위가 같은 클래스를 상속한다는 느낌이라 생각해 주시면 좋을 것 같습니다. 따라서 유지보수 비용을 증가시키는 불이익보단, 같은 기능을 하는 인터페이스를 하나로 묶는 혜택이 더 강할 것이라 생각합니다.
- 클라이언트에는 내리지 않을 특수한 정보라 dunderscore를 붙여 기술했습니다. 생각해보니 `__knownTo?`가 되어야 할 것 같군요.

**Comment by limgit** [comment]
- 첫번째 argument에 대해서는 동의합니다. 혜택 > 불이익인건 맞지만 불이익이 생기는 점이 조금 께름칙했을 뿐이에요 :)
- `SharedInfo` 인터페이스를 사용하면서 `__knownTo` 필드를 사용하지 않는 경우가 있을까요? 해당 필드가 없다는 것은 아무한테도 공유되지 않는다는건데, 그럼 즉 `SharedInfo` 가 아니라는 의미일것 같습니다.

**Comment by JeongHoJeong** [comment]
- 약간 과격하게 표현하자면, 불이익이 조금이라도 생긴다는 점에도 동의하지는 않습니다. 같은 기능을 하는 코드니 같은 기능으로 묶는 것이 당연하다고 생각합니다.
- 프론트도 똑같은 모델을 사용하려면 어쩔 수 없는 선택인 것 같아서 위와 같이 표기하긴 했습니다만, 코드 중복 없이 동일 모델을 사용하면서 `SharedInfo.__knownTo`는 가릴 방법이 있을까요? 그나마 떠오른 대안이 있다면,
```typescript
interface SharedInfo {
  __knownTo: PlayerId[] | null  // `PlayerId[]` if it's server, `null` otherwise
}
```
아니면 한 뎊스 더 들어가서,
```typescript
interface SharedInfo {
  __meta?: {
    knownTo: PlayerId[]
  }  // `__meta` is only visible for server
}
```
`__meta?`로 묶은 이유는 해당 정보에 대해 서버만 알아야 하는 메타정보가 훨씬 더 늘어날 수 있기 때문입니다.

**Comment by limgit** [comment]
어... 제가 `SharedInfo`가 구체적으로 어떻게 사용될지 감이 안와서 그러는데, 적당한 concrete example이 없을까요? `ICard`에 적용된 거라든가..

**Comment by JeongHoJeong** [comment]
@limgit 
개인적인 대화로 나누었던 것을 한번에 정리하기가 힘들어 일단 간단히만 정리하고 예시를 쓰겠습니다.

우선 이야기를 정리하기 위해 처음으로 돌아가자면, 제가 궁극적으로 바라는 모양은 결국 클라이언트와 서버가 동일한 `IGame` 모델을 가지는 것입니다. 그러나 각 플레이어는 알아야 하는 값만을 알아야 하고, 서버는 모든 정보를 다 들고 있어야 합니다.

따라서 `SharedInfo`라는 이름이 적절하지 않아 보여 `PrivateInfo`로 바꿨습니다. 아래는 논의를 통합한 결과입니다.

```typescript
namespace NotABean {
  type PlayerID = number

  interface IPrivateInfo<PrivateType, PublicType> {
    __meta: {
      knownTo: PlayerID[],
      knownToEveryone?: boolean,
    } | null
    private?: PrivateType
    public: PublicType
  }

  const enum CardType {
    NUMBER = 'NUMBER', SPECIAL = 'SPECIAL',
  }

  const enum SpecialCardValue {
    NEGATION = 'NEGATION', DOUBLE = 'DOUBLE', ZEROING = 'ZEROING',
  }

  type CardBase<C extends CardType, V> = IPrivateInfo<
    {
      suit: number,
      type: C,
      value: V,
    },
    {
      isMouseOn: boolean,
    }
  >

  type Card =
    CardBase<CardType.NUMBER, number> |
    CardBase<CardType.SPECIAL, SpecialCardValue>

  interface IBoard {
    cardsPlayed: Array<{
      playerId: number,
      card: Card,
    }>
  }

  interface IPlayer {
    playerID: PlayerID
    hand: Card[]
  }

  interface IGame {
    players: IPlayer[]
    board: IBoard
  }
}
```

아래는 위 모델을 바탕으로 서버와 플레이어의 관점에서, 같은 `IGame`에 대해 각자의 상태 트리가 어떻게 그려지는지를 묘사해 봤습니다.

```typescript
const server: IGame = {
  board: {
    cardsPlayed: [
      {
        card: {
          __meta: {
            knownTo: [],
            knownToEveryone: true,
          },
          private: {
            suit: 0,
            type: CardType.SPECIAL,
            value: SpecialCardValue.DOUBLE,
          },
          public: {
            isMouseOn: false,
          },
        },
        playerId: 1,
      },
    ],
  },
  players: [
    {
      hand: [
        {
          __meta: {
            knownTo: [1],
          },
          private: {
            suit: 0,
            type: CardType.NUMBER,
            value: 2,
          },
          public: {
            isMouseOn: false,
          },
        },
      ],
      playerID: 1,
    },
    {
      hand: [
        {
          __meta: {
            knownTo: [2],
          },
          private: {
            suit: 0,
            type: CardType.NUMBER,
            value: 3,
          },
          public: {
            isMouseOn: false,
          },
        },
      ],
      playerID: 2,
    },
  ],
}

const player1: IGame = {
  board: {
    cardsPlayed: [
      {
        card: {
          __meta: null,
          private: {
            suit: 0,
            type: CardType.SPECIAL,
            value: SpecialCardValue.DOUBLE,
          },
          public: {
            isMouseOn: false,
          },
        },
        playerId: 1,
      },
    ],
  },
  players: [
    {
      hand: [
        {
          __meta: null,
          private: {
            suit: 0,
            type: CardType.NUMBER,
            value: 2,
          },
          public: {
            isMouseOn: false,
          },
        },
      ],
      playerID: 1,
    },
    {
      hand: [
        {
          __meta: null,
          public: {
            isMouseOn: false,
          },
        },
      ],
      playerID: 2,
    },
  ],
}
```

**Comment by limgit** [comment]
아주 좋습니다 생각하고 있던 프로그램 구조와 완전히 일치하는 스키마를 만드셨네요 👍 고생하셨습니다. 
한가지 궁금한 점은, `__meta`에 `knownTo`와 `knownToEveryone` 필드가 모두 있을 필요가 있는지입니다. 정보의 중복으로 보이는 것 같거든요. 각 클라에 PrivateInfo를 보낼 때 `__meta.knownTo` 필드를 참조해서 클라이언트에 해당하는 플레이어 아이디가 있는 경우에 보내는 식으로 돌아갈 것 같은데 `knownToEveryone`이 필요할까요? 더해서 data inconsistency가 발생할 가능성도 있어 보이구요.


마지막으로 이제 각 플레이어가 획득한 (즉 점수계산에 쓰일) 카드가 어디에 들어갈 지 결정하면 될 것 같습니다. 바닥에 깔려있는 카드라는 점에선 `IBoard`에, 플레이어가 획득했다는 점에 집중하면 `IPlayer`쪽에 속하는 것이 맞을거 같은데 어떻게 생각하시나요? 개인적으론 `IPlayer`쪽이 더 말이 되는거 같다고 생각하긴 합니다.

**Comment by limgit** [comment]
1. 이슈 분리에 동의합니다. 슬슬 이슈 맨 밑으로 내리는 것도 일이더군요. 다만 `IGame` 인터페이스 설계와 `NotABean.IPhase` 설계 이슈까지 분리할 필요는 없어보입니다. `IGame` 설계쪽 이슈 대부분의 내용이 `cardsAcquired` 관련 내용 일부랑 `NotABean.IPhase` 설계 이슈 내용일 것 같거든요.  내용 길어지면 그때 또 나눠도 될것 같기도 하구요.
만일 `IGame`의 설계 논의에 위 내용 말고도 더 논의할 내용이 있다고 하면 미리 나누어 두는 쪽이 더 괜찮을 것 같네요.
2. 음... `knownTo`에 모든 플레이어를 하나하나 넣는것이 크게 문제될 이유가 있을까요? 처음부터 제가 생각하고 있던 방식이라 저는 오히려 `knownToEveryone`이 부자연스럽다 느껴서 그렇습니다.
3. `cardsAcquired` 굉장히 마음에 드네요 👍 👍

**Comment by limgit** [comment]
넵 분리후에 분리해서 생긴 이슈에서 이쪽으로 reflink 걸어주면 쌍방 참조 가능해지니까 닫아도 무방할 것 같습니다~

**Comment by JeongHoJeong** [comment]
#34 와 #35 에서 논의를 이어가겠습니다. 이 이슈는 여기서 닫습니다.
