### ISSUE TITLE
이슈 템플릿이 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/web-lab#21]
# 설명
PR 템플릿이 있으니 이슈 템플릿도 있으면 좋겠습니다.

> # 설명

당장은 이 수준이어도 괜찮을 것 같은데 어떨까요?

**Comment by limgit** [comment]
개요 문단 정도는 있는것도 괜찮을 것 같습니다

> # 개요
> 
> # 설명

**Comment by JeongHoJeong** [comment]
굿굿

**Comment by limgit** [comment]
아 그리고 이슈 템플릿에 간단히 이슈 작성시의 주의사항도 병기해두는게 좋을 것 같습니다. 예를 들어서

> [이슈 등록 시, 적절한 레이블 및 프로젝트를 등록해주세요.]
> # 개요
> 
> # 설명

같은 형태가 어떨까요?

**Comment by JeongHoJeong** [comment]
굿입니다. 정말 별 거 아니긴 한데 소괄호 대신 대괄호로 하신 이유가 있나요?

**Comment by limgit** [comment]
어... 그냥 별 이유는 없습니다. 쉬프트 안누르고 쓸수 있는 괄호라서...?

**Comment by JeongHoJeong** [comment]
그렇군요ㅋㅋㅋ 크게 상관 없습니다만, 소괄호가 부연설명의 의미에 있어서는 좀 더 일반적인 문장부호지 않을까 싶었습니다.
