### ISSUE TITLE
레이블 정리가 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/web-lab#22]
# 설명
쓰지 않는 레이블이 너무 많습니다. 사용할 레이블과 쓸 레이블을 분리할 필요가 있습니다.

**Comment by limgit** [comment]
정리하면서 각 레이블에 Description도 달아두는게 좋을 것 같습니다. 레이블 달 때 보여서 사용하기 편하네요

**Comment by JeongHoJeong** [comment]
좋습니다. 당장 필요한 것은 `devops`랑 `mvp` 내지는 `feature` 정도가 있을 것 같아요.
`mvp`를 둘지 아니면 전부 `feature`로 몰지는 잘 모르겠습니다.

**Comment by limgit** [comment]
주로 Issue 및 PR 페이지를 사용하고, 굳이 Project에 들어가서 보는 것보다는 레이블을 통해 이슈를 분류하고 관리하는 쪽이 동일한 효과를 누릴 수 있으면서도 접근성 및 관리 비용의 측면에서 이득이 된다고 판단하여 Project board의 사용을 중지할까 합니다. 개략적으로 생각하고 있는 레이블링 시스템은 다음과 같습니다.

- **Project**: 해당 이슈가 속한 사이드 프로젝트의 이름을 기술합니다. 모든 이슈가 필수적으로 가져야 하는 레이블입니다. 어떠한 사이드 프로젝트에도 속하지 않은 이슈의 경우 (ex. CI 설정 이슈) WebLab 프로젝트에 속한 것으로 간주합니다. Prefix로 `project/` 를 사용합니다.
   - `project/web-lab`: 기본 프로젝트
   - `project/not-a-bean`: not a bean 보드게임 개발 사이드 프로젝트
- **Characteristics**: 해당 이슈의 성격을 기술합니다. 이 레이블 역시 모든 이슈가 필수적으로 가져야 할지 여부는 아직 결정하지 못했습니다. 특별히 Prefix를 가지지 않습니다.
   - `dev-ops`: 데브옵스 관련 이슈
   - `bug`: 버그 이슈
   - `feature`: 피쳐 이슈
- **ETC**: 다른 무언가가 더 필요할 수 있습니다.

본 스키마는 프로토타입이니 여기서 수정이 더 필요할 수 있습니다. 의견 많이 제시해주세요. 레이블 이름을 일단 케밥 케이싱으로 작성해놨는데 그냥 케이싱을 쓰지 않고 띄어쓰기를 사용하는 법도 있습니다.

in progress 관련 레이블을 만들지 고민했었는데, Assignee가 붙은 이슈는 in progress인거로 간주하면 될 것 같아서 굳이 작성하지 않았습니다.

이 경우, Project board의 이름은 Project 타입의 레이블로, To do 리스트는 open 된 이슈의 리스트로, In Progress 리스트는 open 되었으며 assignee가 있는 이슈의 리스트로, Done 리스트는 close된 이슈의 리스트로 대응되게 됩니다.

**Comment by JeongHoJeong** [comment]
- 많은 인원이 높은 복잡도로 작업하는 환경이 아니므로, 관리 비용을 낮추는 적절한 방법인 것 같습니다.
- 개발자적인 마인드로, 키워드는 항상 뭔가 whitespace를 delimiter로 하는 단어로 붙어 있어야 할 것 같기에 케밥 케이싱에 찬성합니다.
- `dev-ops`는 `web-lab` 프로젝트가 존재하는 이상 크게 필요하진 않아 보입니다. 지금까지 `dev-ops` 이슈로 보아왔던 이슈들은 `web-lab`의 `feature` 이슈로 해석하는 편이 어떨까 싶습니다. 

코멘트하지 않은 모든 부분에 대하여는 동의합니다. 고민 많이 하신 것 같네요 👍

**Comment by limgit** [comment]
음 `dev-ops`를 `web-lab`의 `feature`로 해석하는 방향 자체는 괜찮다고 생각하는데, 이러면 레이블을 이용한 필터링을 사용할 때 조금 문제가 되지 않을까요? `feature` 레이블을 가진 이슈만을 모았을 때 가운데 devops 관련 내용이 끼어있으면 조금 이상할 것 같습니다. 뭐.. 정 검색하고자 하면 is:issue label:feature -label:project/web-lab 으로 레이블 exclusion을 사용할 수는 있겠지만요

**Comment by JeongHoJeong** [comment]
그런 이슈가 있군요. 전 그런데 프로젝트별로 레이블 and 검색을 하는 편이 맞다는 생각이 듭니다. 따라서 `label:project/foo label:feature` 식으로 검색하는 편이 맞을 것 같다고 생각합니다. 어떤 프로젝트이든 관계 없이 그냥 `feature`만 보고 싶은 니즈는 드물 것 같아서요.

**Comment by limgit** [comment]
그렇게 보면 그게 맞는것 같네요. 그럼 일단 이대로 가겠습니다. 

이 이슈도 제가 작업하도록 하겠습니다. 우선은 위에 써둔 스키마대로 레이블을 만들고 기존 이슈를 이에 따라 분류하겠습니다.

만약 나중에 mandatory label이 따로 더 추가되거나 하면 project 레이블에 쓰인것과 비슷하게 prefix를 설정해서 레이블을 만들어주면 될 것 같고 (category라는 필수 레이블 분류를 만들고자 하면 `category/` prefix를 만드는 식), 그 외의 경우엔 필요할때마다 레이블 추가해서 사용하면 될 것 같네요!

**Comment by limgit** [comment]
@JeongHoJeong 일단 레이블링 시스템 개편 마쳤습니다.

개편하면서 추가로 든 생각인데, 이 이슈처럼 연관된 PR이 생기기 힘든 이슈의 경우 작업을 완료했고, 리뷰를 기다리고 있음을 나타내는 레이블이 하나 필요할 것 같습니다.
본래
- To do: Open Issue
- In progress: Open Issue with Assignee
- Done: Closed Issue

으로 대응하려 했으나 실제로는
- To do: Open Issue
- In progress: Open Issue with Assignee
- Review needed
   - Open Issue with Assignee + Related PR with review requested or
   - Open Issue with Assignee labeled as <some_label>
- Done: Closed Issue

의 형태가 되어야 할 것 같습니다. 근데 써놓고 보니 또 Review needed 에서만 두갈래로 케이스가 나뉘는게 좋아보이지 않네요. 아이디어 있으시면 말씀해주세요 😭 

P.S. #13, #14 의 경우 `infra` 레이블이 달려있지 않아 일단 `project/web-lab` 레이블만 달아두었습니다. `feature`를 추가로 다는게 맞다고 생각하시면 달아주세요

**Comment by JeongHoJeong** [comment]
코드 작업이 없는데 리뷰를 해야 하는 경우는 상당히 적을 것 같습니다. 특수한 예외 케이스로 두는 것으로도 충분하지 않을까요? 이슈에서의 대화로도 현재는 맥락을 충분히 파악할 수 있으니, 모든 경우를 완벽하게 커버할 필요까지는 없을 것 같습니다.

레이블링 작업 수고하셨어요!

**Comment by limgit** [comment]
넵 그럼 이 이슈는 닫도록 하겠습니다 :)
