### ISSUE TITLE
README.md의 배포 문단 삭제가 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/web-lab#24]
# 설명
현재는 #12 이슈가 해결되어 `master` 브랜치에 머지가 일어나면 Heroku에 자동으로 배포가 일어나기 때문에 수동 배포가 필요하지 않습니다.

혹은 배포는 `master` 머지시 자동으로 이루어진다는 내용을 README에 적는 것도 방법일 것 같습니다.

**Comment by limgit** [comment]
아 그렇네요 이거 README 보면서 계속 생각했던건데 까먹었다;;;;
