### ISSUE TITLE
현재 저장소의 이름을 web-lab으로 변경해야 합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/web-lab#25]
# 설명
토의 결과 현재 저장소의 목적성을 다음과 같이 변경하기로 했습니다.
> 여러 웹 서브 프로젝트를 빠르게 만들고 실험해보기 위한 저장소

따라서 다음 작업이 필요합니다.
- 저장소의 이름을 `web-lab`으로 변경합니다.
- Heroku integration이 문제 없는지 확인합니다.
- `README.md`를 업데이트합니다.

훑어보시고 문제 없다면 thumbs up 한 번만 부탁드립니다. @limgit

**Comment by limgit** [comment]
아 방금 생각났는데 저장소 디스크립션도 변경해야합니다

**Comment by JeongHoJeong** [comment]
Heroku 앱의 이름은 `binarysound-web-lab`으로 변경했습니다. 혹시 다른 안 있으신가요?
https://dashboard.heroku.com/apps/binarysound-web-lab

**Comment by limgit** [comment]
괜찮은 것 같습니다!
