### ISSUE TITLE
IGame 인터페이스 설계가 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/web-lab#34]
# 개요
#19 의 논의에서 `IGame` 인터페이스만을 별도로 설계하기 위한 이슈입니다.

# 설명
현재 브랜치 [`iss-19`](https://github.com/binarysound/web-lab/tree/iss-19)의 `app/not-a-bean/models/index.ts`에 논의한 바가 저장되어 있습니다.

namespace `NotABean`과 `IGame` 인터페이스를 완성하는 것이 이 이슈 논의의 목표입니다.

## 현재 상태
이슈 논의에 따라 이 본문을 지속적으로 업데이트하겠습니다.
```typescript
namespace NotABean {
  type PlayerID = number

  interface IPrivateInfo<PrivateType, PublicType> {
    __meta: {
      knownTo: PlayerID[],
    } | null
    private?: PrivateType
    public: PublicType
  }

  const enum CardType {
    NUMBER = 'NUMBER', SPECIAL = 'SPECIAL',
  }

  const enum SpecialCardValue {
    NEGATION = 'NEGATION', DOUBLE = 'DOUBLE', ZEROING = 'ZEROING',
  }

  interface ICardBase<C extends CardType, V> {
    suit: number,
    type: C,
    value: V,
  }

  type CardInHand = IPrivateInfo<Card, {
    isMouseOn: boolean,
  }>

  type Card =
    ICardBase<CardType.NUMBER, number> |
    ICardBase<CardType.SPECIAL, SpecialCardValue>

  interface IBoard {
    cardsPlayed: Array<{
      playerId: number,
      card: Card,
    }>
  }

  interface IPlayer {
    playerID: PlayerID
    hand: CardInHand[]
    cardsAcquired: Card[]
  }

  export interface IGame {
    players: IPlayer[]
    board: IBoard
  }
}
```

**Comment by JeongHoJeong** [comment]
https://github.com/binarysound/web-lab/issues/19#issuecomment-420934166

에서 말씀하신 대로, 지금 상태에서 `knownToEveryone?` 프로퍼티는 필요 없어 보입니다. 우선 제거하도록 하겠습니다.
게임의 phase는 어떻게 나눠볼 수 있을까요? 제가 룰에 대한 정확한 감은 없어 간단히나마 틀을 잡아 주시면 좋을 것 같습니다. @limgit

**Comment by limgit** [comment]
현재 개인적으로 생각하고 있는 구조는 '특정 `phase`일 때는 특정 `action`만을 인식하며, 특정 `action`이 주어지면 다른 특정 `phase`로 이동한다' 인데, 혹시 생각하고 계신것과 다른 부분이 있다면 말씀해 주세요.

게임의 규칙을 수도코드화 하면 아래와 같습니다:
```
function game(players):
  initialPlayer = selectRandom(players)
  while (not allCardsAreUsed):
    cardsPlayed = []
    cardsPlayed.append(waitForCard(initialPlayer))
    cardsPlayed.append(waitForCards(allPlayers except initialPlayer))
    openCards()
    selectingPlayer = initialPlayer
    while (cardsPlayed != []):
      selectedCard = waitForSelection(selectingPlayer, cardsPlayed)
      assert( len(cardsPlayed) > 1 xor selectedCard.originalOwner == initialPlayer )
      cardsPlayed.remove(selectedCard)
      selectingPlayer.cardsAcquired.append(selectedCard)
      if cardsPlayed == []:
        initialPlayer = selectingPlayer
      selectingPlayer = selectedCard.originalOwner
  scores = {}
  foreach player in players:
    suitScore = {}
    foreach card in player.cardsAcquired:
      if card.type == NUMBER:
        suitScore[card.suit] += card.value
    foreach card in player.cardsAcquired:
      if card.type == SPECIAL:
        if card.value == NEGATION: suitScore[card.suit] = -suitScore[card.suit]
        if card.value == DOUBLE: suitScore[card.suit] *= 2
        if card.value == ZEROING: suitScore[card.suit] = 0
    scores[player] = sum(suitScore.values())
  rankPlayerByScore(scores)
```
위 수도 코드에서 유저의 액션을 받는 부분(`wait` prefix 가 붙는 function call)을 중심으로 살펴보면
1. 라운드의 시작
2. 선 플레이어의 카드 제출
3. 이외 플레이어의 카드 제출
4. 바닥에 남은 카드가 없을 때까지
   - 선택할 차례 플레이어의 카드 선택

의 반복임을 알 수 있습니다. 따라서 제가 생각하고 있는 각 `phase` 및 해당 `phase`에서 수용 가능한 액션과 그 액션의 결과로 이동하는 `phase`는 다음과 같습니다:
- `phase 1`: 최초 라운드 상태
   - 선 플레이어의 카드 제출: `phase 2`로 이동
- `phase 2`: 선 플레이어가 카드를 제출한 이후
   - 이외 플레이어의 카드 제출
      - 모든 플레이어가 제출한 경우: `phase 3`로 이동
      - 그 외 경우: `phase 2`로 이동
- `phase 3`: 카드 선택 단계
   - 현재 선택중인 플레이어의 카드 선택
      - 모든 플레이어가 카드를 선택하였으며, 모든 카드가 소진된 경우: `phase 4`로 이동
      - 모든 플레이어가 카드를 선택하였으나, 모든 카드가 소진되지는 않은 경우: `phase 1`로 이동
      - 그 외 경우: `phase 3`로 이동
- `phase 4`: 게임 종결 단계
  - 별다른 액션을 수용하지 않으며, 점수 계산 및 게임 결과 산출

도식화하면 다음과 같습니다:
![image](https://user-images.githubusercontent.com/10260432/45526202-2fc20780-b811-11e8-9bce-7ee91844e49f.png)


작성하면서 살펴보다 깨달은건데, 굳이 `phase`를 넣지 않아도 그냥 상태트리의 상태만 봐서 현재 게임이 어느 상태에 있는지의 정보는 `selectingPlayer`와 `initialPlayer` 정도의 정보만 포함해줘도 충분히 알 수 있을 것 같네요. `initialPlayer`는 선 플레이어의 id를 저장하고, `selectingPlayer`의 값은 카드 선택 단계 이외에서 `null`, 카드 선택 단계에서는 다음에 선택권을 가진 플레이어의 id가 되면 될 것 같습니다. 이러면 상태 트리에 따라 게임이 아래와 같이 진행되겠네요.
- `IBoard.cardsPlayed` 가 비어있는 경우 & `selectingPlayer == null`: `initialPlayer`에 해당하는 플레이어가 카드를 낼 차례
- `IBoard.cardsPlayed` 의 원소가 한 개 이상 플레이어 수 미만일 경우 & `selectingPlayer == null`: `initialPlayer` 이외의 플레이어가 카드를 낼 차례
- `IBoard.cardsPlayed` 의 원소가 플레이어 수만큼 있을 경우 & `selectingPlayer == null`: 카드를 공개하고 `selectingPlayer`를 `initialPlayer`로 설정. 카드 선택 시작
- `IBoard.cardsPlayed` 의 원소가 두 개 이상일 경우 & `selectingPlayer != null`: `selectingPlayer`가 카드를 선택할 차례. `initialPlayer`가 제출한 카드는 고를 수 없으며, 선택된 카드를 제출한 사람이 다음 `selectingPlayer`가 됨
- `IBoard.cardsPlayed` 의 원소가 한 개일 경우 & `selectingPlayer != null`: `selectingPlayer`가 `initialPlayer`의 카드를 가져가고, 
   - 모든 플레이어의 핸드가 없다면: 게임 종결 단계로 넘어가 점수 계산
   - 그 외의 경우: `initialPlayer = selectingPlayer`, `selectingPlayer = null`이 됨

이 경우를 도식화하면 다음과 같습니다. 편의상 `IBoard.cardsPlayed`는 `cardsPlayed`로 축약했고, 플레이어 수는 `n`으로 표시했습니다:
![image](https://user-images.githubusercontent.com/10260432/45526856-e921dc80-b813-11e8-8fcd-65e6bc296b23.png)


작성해둔 [위키](https://github.com/binarysound/web-lab/wiki/Not-A-Bean-Rules) 참조해주세요.

**Comment by JeongHoJeong** [comment]
일단 코멘트의 퀄리티에 놀라고 시작합니다.... ㅋㅋㅋㅋ 읽는 데 시간 좀 걸리겠군요. 작성하시느라 수고하셨습니다. 👏

**Comment by JeongHoJeong** [comment]
1. phase는 커뮤니케이션한대로 매번 연산하기보다는 상태 트리에 넣어 두는 편이 코드 가독성과 연산 캐싱 측면에서 유리할 것 같습니다. data inconsistency가 발생할 우려가 있긴 하나, 클라이언트도 매번 페이즈를 알기 위해 연산해야 했을 때 컴퓨팅 리소스가 많이 들기 쉽고, 페이즈가 복잡한 로직으로 구분되면 유지보수가 힘들어질 것 같기도 합니다.
2. phase 이름을 정확히 지어서 커뮤니케이션하고 코드에 쓰는 편이 좋을 것 같습니다. 예를 들자면 `WaitingForFirstPlayerToPlay`, `WaitingForOtherPlayersToPlay`, `WaitingForPlayersToSelectCardOnBoard`, `End` 정도로요.
3. 위 말씀하신 내용을 `InGamePhase`로 구분하거나, 아니면 게임 외 상태일 때의 페이즈 표현도 필요할 것 같습니다. `WaitingForGameToStart` 정도가 필요하다고 느꼈습니다.

이 외는 아주 좋은 것 같습니다. 이제 비즈니스 로직을 짤 수 있을 것 같네요. @limgit

**Comment by JeongHoJeong** [comment]
혹시 이 이슈와 #35 의 구현 작업을 진행해주실 수 있으신가요? `app/not-a-bean` 밑에 작업이 들어가면 될 것 같습니다. @limgit

**Comment by limgit** [comment]
제가 여기서 쓰이고 있는 스택을 기반으로 뭔갈 만들어보는건 처음이라 기초 작업을 끝내서 PR을 일단 오픈해두고 거기서 교정받아가면서 작업할까 하는데 그렇게 해도 괜찮을까요?

더해서, 아직 #13, #14 가 해결되지 않은 상태지만 작업에 들어가도 괜찮은건가요? 비즈니스 로직이라 상관 없는거 같긴 한데...
@JeongHoJeong

**Comment by JeongHoJeong** [comment]
@limgit 일단 브랜치에 작업물을 올려주시고, PR을 WIP 상태로 열어주신 후 작업을 계속 진행해주시면서 개인 메신저로 이야기를 나누면 될 것 같습니다. 또한, 게임 로직은 메인 로직과 아무 연결 없이 순전히 독립적으로 순수 함수 기반으로 작성될 수 있기 때문에 아무 문제 없을 것 같습니다!
