### ISSUE TITLE
게임의 액션에 대한 논의가 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/web-lab#35]
# 개요
#19, #34 에서 논의중인 `IGame` 인터페이스에 대하여, 플레이어가 취할 수 있는 액션들을 정의하고 해당 액션의 효과를 정의하기 위한 이슈입니다.

# 설명
기본적인 타입 시스템은 다음과 같이 구상하고 있습니다.

```typescript
const enum GameActionType {
  PlayCard,
  AnotherAction,
  /* other types ... */
}

interface IGameActionBase<T extends GameActionType, P> {
  type: GameActionType
  payload: P
}

type GameAction =
  IGameActionBase<GameActionType.PlayCard, {
    playerId: NotABean.PlayerId,
    card: NotABean.Card,
  }> |
  IGameActionBase<GameActionType.AnotherAction, { /* ... */ }>

// We need to implement a pure function of type `ApplyAction` which will be the engine of this game.
type ApplyAction = (game: NotABean.IGame, action: GameAction) => NotABean.IGame 
```

따라서 이 이슈에서 논의해야 할 것들은

1. 위 구조의 확정
2. 필요한 `GameActionType`과 해당하는 `payload`의 정의

가 되겠습니다.

**Comment by limgit** [comment]
일단 `GameActionType`은 바로 확정지을 수 있을것 같네요. 플레이어가 이 게임에서 할 수 있는 행동은
1. 카드를 제출한다
2. 카드를 선택한다

뿐이기 때문에
```typescript
const enum GameActionType {
  PlayCard,
  SelectCard
}
```
면 충분할 것 같습니다.

그러면.. `payload`를 정의해야 하는데, 지금 써두신대로
```typescript
{
  playerId: NotABean.PlayerId,
  card: NotABean.Card
}
```
면 충분할 것 같습니다. 누가 어떤 카드를 냈는지의 정보만 가지고 있으면 필요한 모든 정보는 다 있으니까요

**Comment by JeongHoJeong** [comment]
액션이 확실히 많이 필요하지는 않겠군요. 다만, 게임을 중간에 포기하는 등의 경우도 생각할 필요가 있지 않을까요?

**Comment by limgit** [comment]
음... 우선 보드게임이 기반이다보니까 그런 예외적인 상황에 대한 생각은 미처 하지 못했네요. 다만 중간에 포기하는 등의 기능을 직접적으로 제공하는게 아니라 응답시간이 초과되었을 때 서버 내부적으로 `GameAbort` 등을 처리하게 해야할 것 같습니다. 이렇게 서버 내부에서 일어나는 행동들도 따로 `GameActionType`에 추가하는게 맞을까요?

**Comment by JeongHoJeong** [comment]
실제 인게임 로직과 외부적인 로직을 분리할 필요가 있다는 말씀이시군요. 공감합니다만, 생각해보면 이 부분은 규칙이 우선적으로 필요할 것 같네요. 게임 중간에 커넥션 중단으로 일부 플레이어가 나가는 것도 분명히 존재할 수 있는 시나리오니, 해당 시나리오도 커버할 수 있도록 게임 로직이 완성되어야 논의가 더 진행될 수 있을 것 같습니다. 가장 간단한 솔루션은 한 플레이어라도 접속이 끊어지면 게임을 끝내는 방법이 있겠네요.

**Comment by limgit** [comment]
제가 처음 생각했던것 역시 단 한플레이어라도 접속이 끊기면 게임 강제 종료 시그널을 보내는 것이었습니다.
개인적인 생각이지만 외부적인 로직을 전부 미리 규칙을 정의하고 들어가는건 너무 스코프가 넓어 불가능에 가까울 것 같으니, 규칙의 추가에 대해서 flexible한 외부 action구조를 우선 짜 두고 하나씩 추가해 나가는게 더 나아보이는데 어떻게 생각하시나요? 이미 현재 `GameActionType` 구조 자체가 충분히 flexible해서 살짝 변형해 그대로 사용해도 괜찮을 것 같긴 합니다.

**Comment by JeongHoJeong** [comment]
흠.. 좋습니다. 일단 최소한의 규칙 세트로 시작해봅시다.
